openapi: '3.0.0'
info:
  version: 'v1'
  title: api-jobs
servers:
  - url: https://pre-api.cloudappi.net/api-jobs/v1
    description: Development server
  - url: https://api.cloudappi.net/api-jobs/v1
    description: Production server
# tags:
#   - name: Account types
#     description: 'Operations and resources related to account types'
#   - name: Customers
#     description: 'Operations and resources related to customers'
#   - name: Customer accounts
#     description: 'Operations and resources related to customer accounts'
#   - name: Monitoring
#     description: 'Operations related to monitoring'
paths:
  /patients:
    x-apigen-binding:
      model: Patient
    get:
      summary: get all patiens for hospital
      operationId: getPatients
      tags:
        - Patients
      parameters:
        - $ref: "#/components/parameters/init_param"
        - $ref: "#/components/parameters/limit_param"
        - $ref: "#/components/parameters/total_param"
        - $ref: "#/components/parameters/select_param"
        - $ref: "#/components/parameters/exclude_param"
        - $ref: "#/components/parameters/expand_param"
        - $ref: "#/components/parameters/order_by_param"
      responses:
        '206':
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/standard_response_patients"
              examples:
                Ejemplo:
                  $ref: '#/components/examples/get_patient_response_example' 
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/standard_response_patients"
              examples:
                Ejemplo:
                  $ref: '#/components/examples/get_patient_response_example' 
    post:
      summary: create a patient
      operationId: createPatient
      tags:
        - Patients
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/new_patient"
      responses:
        '201':
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/standard_response_patient"
              examples:
                Ejemplo:
                  $ref: '#/components/examples/post_patient_response_example'                
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/standard_response_patient"
              examples:
                Ejemplo:
                  $ref: '#/components/examples/client_bad_request_response_example'                   
                
  /patients/search:
    x-apigen-binding:
      model: Patient
    post:
      summary: search a patient 
      operationId: searchPatient
      tags:
        - Patients
      parameters:
        - $ref: "#/components/parameters/init_param"
        - $ref: "#/components/parameters/limit_param"
        - $ref: "#/components/parameters/total_param"
        - $ref: "#/components/parameters/select_param"
        - $ref: "#/components/parameters/exclude_param"
        - $ref: "#/components/parameters/expand_param"
        - $ref: "#/components/parameters/order_by_param"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/standard_search"
      responses:
        '206':
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/standard_response_patients"
  /patients/{id}:
    x-apigen-binding:
      model: Patient
    get:
      summary: get a patient by id
      operationId: getPatient
      tags:
        - Patients
      parameters:
        - $ref: "#/components/parameters/string_id_param"
        - $ref: "#/components/parameters/select_param"
        - $ref: "#/components/parameters/exclude_param"
        - $ref: "#/components/parameters/expand_param"
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/standard_response_patient"
              examples:
                Ejemplo:
                  $ref: '#/components/examples/get_patient_response_example' 
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/standard_response_patient"
              examples:
                Ejemplo:
                  $ref: '#/components/examples/standard_not_found_response_example'                                   
    put:
      summary: update a Patient
      operationId: updatePatient
      tags:
        - Patients
      parameters:
        - $ref: "#/components/parameters/string_id_param"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/update_patient"
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/standard_response_patient"
    delete:
      summary: delete a patient by id
      operationId: deletePatient
      tags:
        - Patients
      parameters:
        - $ref: "#/components/parameters/string_id_param"
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/standard_response_patient"

components:
  parameters:
    string_id_param:
      name: id
      in: path
      required: true
      schema:
        type: string
    init_param:
      in: query
      name: $init
      schema:
        type: integer
        format: int32
    limit_param:
      in: query
      name: $limit
      schema:
        type: integer
        format: int32
    total_param:
      in: query
      name: $total
      schema:
        type: boolean
    select_param:
      in: query
      name: $select
      schema:
        type: array
        items:
          type: string
    exclude_param:
      in: query
      name: $exclude
      schema:
        type: array
        items:
          type: string
    expand_param:
      in: query
      name: $expand
      schema:
        type: array
        items:
          type: string
    order_by_param:
      in: query
      name: $orderby
      schema:
        type: array
        items:
          type: string
  schemas:
    standard_response_result:
      properties:
        result:
          type: object
          properties:
            status:
              type: boolean
              example: true
            http_code:
              type: integer
              example: 200
            errors:
              type: array
              items:
                $ref: '#/components/schemas/standard_error'
            info:
              type: string
              example: Successful request.
            trace_id:
              type: string
              example: b8240028-8df4-4019-8b03-182a0a9bc88d
            num_elements:
              type: integer
              example: 1
          required:
            - status
            - http_code
            - trace_id
    standard_error:
      type: object
      properties:
        code:
          type: integer
          example: 1003
        message:
          type: string
          example: Attribute with value greater than maximum
    standard_search:
      type: object
      properties:
        operation:
          type: string
          enum: [AND, OR, GT, LT, GTEQ, LTEQ, EQ, NEQ, IN, BETWEEN, SUBSTRING, LIKE, ILIKE, NLIKE, REGEXP]
        values:
          type: array
          items:
            type: object
            properties:
              property:
                type: string
              value:
                type: string
              values:
                type: array
                items:
                  type: string

    standard_response_patients:
      allOf:
        - $ref: "#/components/schemas/standard_response_result"
        - type: object
          properties:
            data:
              type: object
              properties:
                patients:
                  type: array
                  items:
                    $ref: "#/components/schemas/patient"

    standard_response_patient:
      allOf:
        - $ref: "#/components/schemas/standard_response_result"
        - type: object
          properties:
            data:
              $ref: "#/components/schemas/patient"

    patient:
      x-apigen-mapping:
        model: Patient
      type: object
      required:
        - id
        - name
        - surname        
      properties:
        id:
          type: string
          example: '6152f5065e6a5d0530211f77'
        name:
          type: string
          example: 'John'
        surname:
          type: string
          example: 'Doe'
    new_patient:
      x-apigen-mapping:
        model: Patient
      type: object
      required:
        - name
        - surname
      properties:
        name:
          type: string
          example: 'Johnny'
        surname:
          type: string
          example: 'Doey'
    update_patient:
      x-apigen-mapping:
        model: Patient
      type: object
      properties:
        name:
          type: string
          example: 'Evan'
        surname:
          type: string
          example: 'Gion'
  examples:
    post_patient_response_example:
      value:
        result:
          status: true
          http_code: 201
          info: 'Created'
          trace_id: b8240028-8df4-4019-8b03-182a0a9bc88d                    
        data:
          id: '6152f5065e6a5d0530211f77'
          name: 'John'
          surname: 'Doe'    
    get_patient_response_example:
      value:
        result:
          status: true
          http_code: 200
          info: 'OK'
          trace_id: b8240028-8df4-4019-8b03-182a0a9bc88d                    
        data:
          id: '6152f5065e6a5d0530211f77'
          name: 'John'
          surname: 'Doe'  
    standard_not_found_response_example:
      value:
        result:
          status: false
          http_code: 404
          info: 'Not found'
          trace_id: b8240028-8df4-4019-8b03-182a0a9bc88d
          errors:
          - code: 1104
            message: 'No item was found with the identifier provided. Please review:% s'                           
    client_bad_request_response_example:
      value:
        result:
          status: false
          http_code: 400
          info: 'Bad Request'
          trace_id: b8240028-8df4-4019-8b03-182a0a9bc88d
          errors:
          - code: 1000
            message: Attribute '% s' cannot contain a null value

  # x-apigen-models:
  #   Patient:
  #     relational-persistence:
  #       table: patients
  #     attributes:
  #       - name: id
  #         type: String
  #         relational-persistence:
  #           primary-key: true
  #           autogenerated: true
  #       - name: name
  #         type: String
  #         validations:
  #           - type: NotEmpty
  #       - name: surname
  #         type: String
  #         validations:
  #           - type: NotEmpty
  #       - name: stays
  #         type: Array
  #         items-type: Stay
  #         relational-persistence:
  #           foreign-column: patient_id